### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by Lzsh1** [monSteRhhe/bilibili-dynamic-del#2]
点击自动判断没有反应

**Comment by monSteRhhe** [comment]
已经修改了，可以试试能不能用了

**Comment by Lzsh1** [comment]
好像还是不行

**Comment by monSteRhhe** [comment]
更新到最新的了吗

**Comment by Lzsh1** [comment]
更新了啊，是最新的

**Comment by monSteRhhe** [comment]
奇怪了，我这边还是能正常用的，我用的是Edge+黑猴子/脚本猫，我这边正常用倒是不好找问题出在哪儿
脚本运行之后有发出通知吗，黑猴子和脚本猫运行应该都是能发出通知的

**Comment by Lzsh1** [comment]
我使用的也是edge油猴，打开bilibili之后点击自动判断之后就没有反应

**Comment by monSteRhhe** [comment]
需要删除的动态是带有“互动抽奖”的吗，不是那种有倒计时开奖的“互动抽奖”功能的动态还是没办法判断删除的

**Comment by monSteRhhe** [comment]
> 需要删除的动态是带有“互动抽奖”的吗，不是那种有倒计时开奖的“互动抽奖”功能的动态还是没办法判断删除的

动态页的链接可以发我看看都是不是可以删除的

**Comment by Lzsh1** [comment]
![截屏2023-06-20 10 02 35](https://github.com/monSteRhhe/bilibili-dynamic-del/assets/74004927/2782889c-fa21-4783-89e9-948d20ec91cb)
类似这种的删除不掉吗

**Comment by monSteRhhe** [comment]
> ![截屏2023-06-20 10 02 35](https://user-images.githubusercontent.com/74004927/246985561-2782889c-fa21-4783-89e9-948d20ec91cb.png) 类似这种的删除不掉吗

对的，能自动删除的是那种B站提供了“互动抽奖”功能的，能判断已经开奖的动态然后删除，这种的就不好判断
